env:
  APP_VERSION: v1.0

# values.yaml
serviceAccount:
  create: true
  automount: true
  annotations:
    key1: value1
    key2: value2

# values.yaml
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70
